FROM node:26-alpine3.23 As builder
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install

FROM node:26-alpine3.23
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
ENV MONGO_URL="mongodb://mongo:27017/catalogue" \
    MONGO="true"
WORKDIR /opt/server
USER roboshop
COPY --from=builder /opt/server /opt/server
CMD ["node","server.js"]
